-- Ajout des informations légales du tenant
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS ninea VARCHAR(50);
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS rc VARCHAR(50);
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS website VARCHAR(200);
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS city VARCHAR(100);
ALTER TABLE tenant ADD COLUMN IF NOT EXISTS zip_code VARCHAR(20);